import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const umdPath = resolve(
  __dirname,
  "..",
  "node_modules",
  "chart.js",
  "dist",
  "chart.umd.js",
);

const content = readFileSync(umdPath, "utf-8");
const escaped = JSON.stringify(content);

const output = `// Generated by scripts/vendor-chartjs.mjs — do not edit manually
export const CHART_JS = ${escaped};
`;

const outPath = resolve(
  __dirname,
  "..",
  "src",
  "report",
  "templates",
  "chartjs-bundle.generated.ts",
);

writeFileSync(outPath, output, "utf-8");
console.log(`Written ${(content.length / 1024).toFixed(0)} KB to ${outPath}`);
